apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: admin-api
spec:
  template:
    spec:
      containers:
        - image: ${ADMIN_API_DOCKER_IMAGE}
          env:
            - name: ADMIN_AUTH_PROJECT_ID
              value: ${ADMIN_AUTH_PROJECT_ID}
            - name: ADMIN_AUTH_TENANT_ID
              value: ${ADMIN_AUTH_TENANT_ID}
