apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: admin-api
spec:
  template:
    spec:
      containers:
        - image: ${DOCKER_IMAGE_DIGEST}
          env:
            - name: ADMIN_AUTH_PROJECT_ID
              value: ${ADMIN_AUTH_PROJECT_ID}
            - name: ADMIN_AUTH_TENANT_ID
              value: ${ADMIN_AUTH_TENANT_ID}
#            - name: DB_URL
#              valueFrom:
#                secretKeyRef:
#                  name: DB_URL
#                  key: latest
