name: backend-template

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "${DOCKER_DB_PORT:-5432}:5432"
    volumes:
      - ./scripts/create-test-db.sql:/docker-entrypoint-initdb.d/create-test-db.sql
