apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: db
spec:
  template:
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          maxRetries: 1
          containers:
            - image: ${DOCKER_IMAGE_DIGEST}
              args:
                - "pnpm"
                - "drizzle-kit"
                - "migrate"
              env:
#                - name: DB_URL
#                  valueFrom:
#                    secretKeyRef:
#                      name: DB_URL
#                      key: latest
