name: Build and Deploy (admin-api)

on:
  push:
    branches:
      # Change if your branches are different
      - main
      - prod
  workflow_dispatch:

permissions:
  contents: read

env:
  GCP_PROJECT: ${{ vars.GCP_PROJECT }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  DOCKER_REPOSITORY: ${{ vars.DOCKER_REPOSITORY }}

jobs:
  build:
    name: Build (admin-api)
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Docker Auth
        run: ./deployment/utils/docker-auth.sh
      - name: Build
        run: ./deployment/admin-api/build.sh

  deploy:
    name: Deploy (admin-api)
    needs:
      - build
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Deploy
        run: ./deployment/admin-api/deploy.sh
