name: Test Docker build caches

on:
  push:
    branches:
      - feature/5-docker-build-caches
  workflow_dispatch:

permissions:
  contents: read

env:
  GCP_PROJECT: ${{ vars.GCP_PROJECT }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  DOCKER_REPOSITORY: ${{ vars.DOCKER_REPOSITORY }}

jobs:
  build:
    name: Build projects
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build projects
        run: npx nx run-many --target=build --all
        env:
          VITE_ADMIN_AUTH_API_KEY: ${{ vars.ADMIN_AUTH_API_KEY }}
          VITE_ADMIN_AUTH_TENANT_ID: ${{ vars.ADMIN_AUTH_TENANT_ID }}
          VITE_ADMIN_API_BASE_URL: ${{ vars.ADMIN_API_BASE_URL }}
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist
          if-no-files-found: "error"

  build_docker-api:
    name: Build docker image (api)
    needs:
      - build
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Docker auth
        run: ./deployment/utils/docker-auth.sh
      - name: Build & Push Docker image
        run: ./deployment/api/build.sh
